### ISSUE TITLE
Issue with secondary calculations like ratio in metric layer.

### ISSUE THREAD

**Issue by DivyaKasala** [flexanalytics/dbt-business-intelligence#10]
When visualizing sales_ratio_to_1_month_ago  of product_monthly metric model in the Flexit BI tool, it is not getting calculated properly. The ratio column in flexit simply sums the value to the level where layout is plotted at. Do We have any option or settings in dbt which will calculate the values on the fly so the calculations like ratios come correctly.

**Comment by ataft** [comment]
This is a major shortcoming of metrics in dbt, and the main reason behind the new [dbt Semantic Layer](https://docs.getdbt.com/docs/use-dbt-semantic-layer/quickstart-semantic-layer). FlexIt does support the dbt Semantic Layer, but unfortunately dbt only supports Snowflake at this time. Here are the FlexIt docs for how to use the dbt Semantic Layer:
https://learn.flexitanalytics.com/docs/dbt_semantic

As you can see, the above scenario is not ideal for metrics, which is why all BI tools act as an on-the-fly semantic layer that calculates and aggregates depending on the selected dimensions. Since dbt metrics and the dbt Semantic Layer are not yet mature, you might want to create metrics in FlexIt at the report or data model levels.
